### ISSUE TITLE
No models show

### ISSUE THREAD

**Issue by Ziov** [ForserX/StableDiffusionUI#11]
I'm trying out this but I'm unable to see any models once added to the models directory

**Comment by ForserX** [comment]
Click "Import" and drop file

**Comment by Ziov** [comment]
They just give errors on trying to import, tried different file types.

**Comment by ForserX** [comment]
Gime me error

**Comment by ForserX** [comment]
Download new release (XUI 3.1.4 Preview.2.7z)
