### ISSUE TITLE
ONNX error

### ISSUE THREAD

**Issue by X3gold** [ForserX/StableDiffusionUI#23]
RTL be like: 19045.10.0
 Name  -  NVIDIA GeForce GTX 1650
 DeviceID  -  VideoController1
 AdapterRAM  -  4293918720
 AdapterDACType  -  Integrated RAMDAC
 Monochrome  -  False
 DriverVersion  -  31.0.15.3598
 VideoProcessor  -  NVIDIA GeForce GTX 1650
 VideoArchitecture  -  5
 VideoMemoryType  -  2
  ${Workspace}\repo\onnx.venv\lib\site-packages\transformers\models\clip\feature_extraction_clip.py:28: FutureWarning: The class CLIPFeatureExtractor is deprecated and will be removed in version 5 of Transformers. Please use CLIPImageProcessor instead.
  You have disabled the safety checker for <class 'diffusers_modules.local.lpw_stable_diffusion_onnx.OnnxStableDiffusionLongPromptWeightingPipeline'> by passing `safety_checker=None`. Ensure that you abide to the conditions of the Stable Diffusion license and do not expose unfiltered results in services or applications open to the public. Both the diffusers team and Hugging Face strongly recommend to keep the safety filter enabled in all public facing circumstances, disabling it only for use-cases that involve analyzing network behavior or auditing its results. For more information, please have a look at https://github.com/huggingface/diffusers/pull/254 .
 Current device: onnx
 txt2img
 SD: Model preload: done
 Load custom vae
 Prompt: 1girl
 Neg prompt: 
 Set seed to 830119422
 txt2img
  
   0%|          | 0/20 [00:00<?, ?it/s]
   5%|5         | 1/20 [00:12<04:06, 12.98s/it]
   5%|5         | 1/20 [00:15<04:46, 15.07s/it]
 Traceback (most recent call last):
   File "${Workspace}\repo\diffusion_scripts\sd_onnx_safe.py", line 109, in <module>
     PipeDevice.MakeImage(pipe, data['Mode'], eta, prompt_tokens + data['Prompt'], prompt_neg_tokens + data['NegPrompt'], data['Steps'], data['Width'], data['Height'], seed, data['CFG'], data['ImgCFGScale'], data['Image'] , data['ImgScale'], data['Mask'], data['WorkingDir'], data['BatchSize'])
   File "${Workspace}\repo\diffusion_scripts\sd_xbackend.py", line 368, in MakeImage
     image=pipe(prompt=[prompt] * batch_size, height=height, width=width, num_inference_steps=steps, guidance_scale=scale, negative_prompt=prompt_neg, eta=eta, generator=rng)
   File "${Workspace}\repo\onnx.venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
     return func(*args, **kwargs)
   File "C:\Users\x3gol\.cache\huggingface\modules\diffusers_modules\local\lpw_stable_diffusion_onnx.py", line 813, in __call__
     noise_pred = self.unet(
   File "${Workspace}\repo\onnx.venv\lib\site-packages\diffusers\pipelines\onnx_utils.py", line 60, in __call__
     return self.model.run(None, inputs)
   File "${Workspace}\repo\onnx.venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 210, in run
     return self._sess.run(output_names, input_feed, run_options)
 onnxruntime.capi.onnxruntime_pybind11_state.Fail

**Comment by ForserX** [comment]
Show main wnd (screen)

**Comment by X3gold** [comment]
What exactly do you mean, about the window of the XUI.exe?

Oh yes, the software asks if you want to update, when I choose no it goes but only slowly because he uses only the CPU and the graphics card not at all also VRAM when I but update, comes the error message from above.

**Comment by ForserX** [comment]
And why do you use ONNX, if you have an NVIDIA GPU?

**Comment by ForserX** [comment]
And also please check that the Device has the necessary GPU.

**Comment by X3gold** [comment]
I just wanted to try this tutorial https://www.youtube.com/watch?v=r-ZYOlZTLDA

**Comment by X3gold** [comment]
I just wanted to try this tutorial https://www.youtube.com/watch?v=r-ZYOlZTLDA
