### ISSUE TITLE
Log bug?

### ISSUE THREAD

**Issue by BraindamageBE** [ForserX/StableDiffusionUI#26]
Hi, 
while XUI is generating images. I constantly get the error message "log file used by another process", while there is no other programm using it.
I tried deleting all the logs to be sure, but the it gets the same with the logs it creates by itself.
If I can manage to stay away from the error messages, I can continue, but as soon as I accidentaly open one, the app crashes.

The programm also doesn't upscale every generated picture.
Maybe it's because those where the ones giving errors?

**Comment by ForserX** [comment]
Check the antivirus.
