### ISSUE TITLE
ONNX

### ISSUE THREAD

**Issue by motorist828** [ForserX/StableDiffusionUI#7]
Why can't I choose ONNX or Vulkan?
I use vega 56 gpu

![Screenshot_43](https://user-images.githubusercontent.com/40582999/230803642-cb45fb92-765f-4ef6-8d25-9871771dc401.png)

**Comment by ForserX** [comment]
Oh. This is the problem of having multiple versions of Python.

U need open (working_dir)\repo in cmd and call:
```
py -3.10 -m venv onnx.venv
onnx.venv\Scripts\activate
pip install -r "..\requirements_onnx.txt"
pip install ort-nightly-directml==1.15.0.dev20230408001 --extra-index-url=https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/ORT-Nightly/pypi/simple/
```

Or wait next release

**Comment by motorist828** [comment]
On the last step I get the error
![Screenshot_44](https://user-images.githubusercontent.com/40582999/230892753-bcad0268-b5ea-41fd-9caa-eb90577f2365.png)

**Comment by ForserX** [comment]
pip install ort-nightly-directml==1.15.0.dev20230408001 --extra-index-url=https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/ORT-Nightly/pypi/simple/

**Comment by ForserX** [comment]
Sorry, my bad

**Comment by motorist828** [comment]
hmm, ONNX is still not available
Is the line "pip install -r "..\requirements_onnx.txt" correct?

i used "pip install -r "requirements_onnx.txt" but not sure if it's correct

![Screenshot_45](https://user-images.githubusercontent.com/40582999/230903555-63393b20-8801-4e67-a0d2-50a0fab71094.png)

**Comment by ForserX** [comment]
Oh... U need use workpath\repo at cmd directory

**Comment by motorist828** [comment]
ok i did all the steps for the repo folder but nothing changed
![Screenshot_46](https://user-images.githubusercontent.com/40582999/230904854-39df24e2-62a0-479f-be91-3a5b23cfe2e0.png)
![Screenshot_47](https://user-images.githubusercontent.com/40582999/230904993-6f6f44df-0f76-4d06-b60c-670cd1cec992.png)

**Comment by ForserX** [comment]
Ohh. U have CUDA. Sorry. It was an instruction for the AMD version

```cpp
py -3.10 -m venv cuda.venv
cuda.venv\Scripts\activate
pip install -r "..\requirements_cuda.txt"
```

**Comment by motorist828** [comment]
![Screenshot_48](https://user-images.githubusercontent.com/40582999/230906415-e0d76ec5-7cd2-4202-b900-6fd6f005f1d1.png)
I don't have CUDA, On my system radeon rx vega 56
I don't know why it is displayed in the program

**Comment by ForserX** [comment]
Oh... Vega don't have "AMD" in GPU name. Okay. I will release a corrected version in an hour or two. I'm sorry for the inconvenience.

**Comment by ForserX** [comment]
https://github.com/ForserX/StableDiffusionUI/releases/tag/3.1.2

**Comment by motorist828** [comment]
I uninstalled the previous version, installed the new one by selecting ONNX during installation
But I am getting this error when I run the generation
![Screenshot_51](https://user-images.githubusercontent.com/40582999/230956926-7846dac5-7442-4cd4-b2c9-b3b536578ef7.png)
![Screenshot_52](https://user-images.githubusercontent.com/40582999/230956996-f3ca2d20-100b-4da4-b899-63d08110e18a.png)

I downloaded the diffusion scripts folder from the repository
now the generation starts but i can see that it only uses the cpu

![Screenshot_53](https://user-images.githubusercontent.com/40582999/230958666-7860b1cd-72e7-4ffb-9d85-1638940a3b69.png)

**Comment by ForserX** [comment]
@motorist828 Monday is a hard day. Fixed the archive.

**Comment by motorist828** [comment]
unfortunately it still doesn't work for my GPU
![Screenshot_54](https://user-images.githubusercontent.com/40582999/230963681-7baa9a9d-acd7-4f88-ad37-955d49b274eb.png)

**Comment by ForserX** [comment]
As I see, the generation has passed and there is a picture on the background.

**Comment by motorist828** [comment]
Yes, but it didn't use my GPU, msi afterburner graph shows 0% load, video ram was also not used

**Comment by ForserX** [comment]
![image](https://user-images.githubusercontent.com/13867290/230964449-8f75e628-3006-4f9a-b5bd-7c80cb4328e1.png)
If he hadn't used it, then you would have generated 5-7 minutes, not 33 seconds.

It's better to just look in the usual Windows task manager.

**Comment by motorist828** [comment]
such time because I used 128x128 pixels knowing about this problem

**Comment by ForserX** [comment]
All right, call in Host wnd
```py
py -install ort-nightly-directml==1.15.0.dev20230408001 --extra-index-url=https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/ORT-Nightly/pypi/simple/ --force
```

After click "Break!" in main form and gen img again

**Comment by motorist828** [comment]
Great, now it works 
![Screenshot_55](https://user-images.githubusercontent.com/40582999/230965714-f053c050-a1da-44de-91d7-c6a345c7e1c0.png)

**Comment by ForserX** [comment]
I was glad to help! Good luck in further generations. If you have any more questions, you can use our server on Discord!
