### ISSUE TITLE
3.1.2 Doesn't download ONNX packages.

### ISSUE THREAD

**Issue by brknsoul** [ForserX/StableDiffusionUI#8]
After running XUI.exe, it asks to install ONNX packages, but instead running an install, it just starts the GUI.

_(Also, 3.1.2's release is called "XUI.3.1.7z", rather than "XUI.3.1.2.7z")_

**Comment by ForserX** [comment]
Do you have python 3.10 installed?

**Comment by brknsoul** [comment]
Yuppers.
![image](https://user-images.githubusercontent.com/1969381/230971413-5ee426e2-3e2a-4cb7-989a-5303c674b80b.png)

**Comment by ForserX** [comment]
Call 
```
py --list
```

**Comment by brknsoul** [comment]
I think i'm missing something;
![image](https://user-images.githubusercontent.com/1969381/230971663-4a8cfb44-54cb-448a-b217-87a4f4746242.png)

**Comment by ForserX** [comment]
Well, that's the root of the problem. There is python, but there is no common name "py" that manages packages

**Comment by brknsoul** [comment]
How do I install py?
Or should I reinstall python 3.10?

**Comment by ForserX** [comment]
Wait a minute. I need to figure out how to overcome this problem once and for all

**Comment by brknsoul** [comment]
Is "py" an alias for "python"?

**Comment by ForserX** [comment]
py - is python launcher.

**Comment by brknsoul** [comment]
Ok, i'm reinstalling python 3.10.11.
I probably missed this;
![image](https://user-images.githubusercontent.com/1969381/230973552-fcb8c5ac-193d-409b-baeb-3f5df49c59cd.png)

EDIT: Ok, now we're cooking!
![image](https://user-images.githubusercontent.com/1969381/230974362-aa0d4775-ffb0-4597-8e97-f5f895a55e70.png)

Excellent! Thanks for the assist for my derp!
![image](https://user-images.githubusercontent.com/1969381/230974638-ac0f5ab4-9c18-4c02-9715-df7908e111f3.png)

Closable.

**Comment by ForserX** [comment]
Eh, and I have already implemented a workaround of the problem.

**Comment by brknsoul** [comment]
I think it's more my fault. I guess a workaround could be simple "install python > custom > ensure py launcher is ticked" in your readme. :-P

**Comment by DuckersMcQuack** [comment]
> I think it's more my fault. I guess a workaround could be simple "install python > custom > ensure py launcher is ticked" in your readme. :-P

I did just that, reinstalled python by ensuring py launcher was added, added to path and all, but i'm still stuck here. It started to download requirements for onnx, then the cmd disappeared and all that's left is these
![image](https://github.com/ForserX/StableDiffusionUI/assets/9039370/9d9b9a42-f727-484d-80b2-833fdd0bda61)

**Comment by ForserX** [comment]
Run 
```cpp
py  -v torch
```
If there is no mistake, then everything is fine
