### ISSUE TITLE
3.1.2: After install and download, models has folders, no files.

### ISSUE THREAD

**Issue by brknsoul** [ForserX/StableDiffusionUI#9]
I didn't see anything in the readme here that suggests I need to populate the models folder myself.
![image](https://user-images.githubusercontent.com/1969381/230983889-f4e7cb5a-670e-4d25-88f0-d32eb831c680.png)

**Comment by ForserX** [comment]
https://github.com/ForserX/StableDiffusionUI/wiki/How-to-use:-Models

**Comment by ForserX** [comment]
Just drop models (.safetensors/.ckpt) to Import form and wait 2 notification for converting done

**Comment by ForserX** [comment]
https://discord.gg/kcXk8sQQ

**Comment by brknsoul** [comment]
Can I use already converted models from another program (onnx-web, for example)?

**Comment by ForserX** [comment]
No

**Comment by brknsoul** [comment]
I was looking at these from huggingface/runwayml/stable-diffusion-v1-5
![image](https://user-images.githubusercontent.com/1969381/230992590-6962ade1-ea0e-42a5-91d3-c5594ac03381.png)

Which do I need? The emaonly or the bigger one?

**Comment by ForserX** [comment]
3/4
